#!/bin/sh

rm *.[ao]
rm *.gcda
rm *.gcno
rm *.gcov
rm *.l[ao]
rm *.loT
rm *.orig
rm *.pc
rm *.py[co]
rm *.rej
rm *.sw[op]
rm *~
rm *#
rm .#*
rm .deps
rm .libs
rm Makefile
#rm Makefile.in
rm _gen
rm ./aclocal.m4
rm -rf ./autom4te.cache
#rm ./compile
rm ./config.cache
#rm ./config.guess
#rm ./config.h
#rm ./config.h.in
rm ./config.log
#rm ./config.status
#rm ./config.sub
#rm ./configure
rm ./depcomp#
#rm ./install-sh
rm ./libtool
#rm ./ltmain.sh
rm ./m4
#rm ./missing
rm ./stamp-h1
rm ./maynard-*.tar.xz
rm ./maynard
rm shell/desktop-shell-client-protocol.h
rm shell/desktop-shell-protocol.c
rm shell/shell-helper-client-protocol.h
rm shell/shell-helper-protocol.c
rm shell/shell-helper-server-protocol.h
rm shell/mod-shell-helper-protocol.c
rm shell/maynard-resources.c
rm shell/maynard-resources.h
rm shell/maynard
rm data/gschemas.compiled
rm data/org.raspberrypi.maynard.gschema.valid
rm data/org.raspberrypi.maynard.gschema.xml
rm po/POTFILES
rm po/stamp-it
